### ISSUE TITLE
Add an icon to the application

### ISSUE THREAD

**Issue by sumanthst24** [sumanthst24/Algo-Expert#6]

**Comment by suprajaLara** [comment]
I will take this issue.

**Comment by sumanthst24** [comment]
Okay you can proceed on this

**Comment by suprajaLara** [comment]
Added the icon for app.
Please check and confirm @sumanthst24 
Here is the link to pull request -> #7

**Comment by suprajaLara** [comment]
Added app icon and updated logo in the splash screen.
Here is the link to pull request -> #9

**Comment by sumanthst24** [comment]
I merged your PR
